import test from 'node:test';import assert from 'node:assert/strict';import {fresh,validate,award,observe,mastery,schedule,dueReviews,createStore,KEY} from '../public/lib/store.js';
test('awards are one-time and observations are separate from XP',()=>{const s=fresh();award(s,'q1',5);award(s,'q1',5);assert.equal(s.xp,5);observe(s,['logic'],true);assert.equal(mastery(s,'logic'),20);observe(s,['logic'],false);assert.equal(mastery(s,'logic'),20)});
test('review success expands spacing and failure contracts it',()=>{const s=fresh();schedule(s,'f1',true);assert.equal(s.reviews.f1.interval,3);schedule(s,'f1',true);assert.equal(s.reviews.f1.interval,6);schedule(s,'f1',false);assert.equal(s.reviews.f1.interval,1);s.reviews.f1.due=0;assert.deepEqual(dueReviews(s),['f1'])});
test('backup round trip retains notes, progress, and settings',()=>{const s=fresh();s.notes.push({id:'n1',text:'Why?',date:'2026-09-07',lesson:'f1',type:'question'});s.lessons.f1={complete:true,stage:6,answers:{q1:{correct:true}}};const r=validate(JSON.parse(JSON.stringify(s)),['f1']);assert.equal(r.notes[0].text,'Why?');assert.equal(r.lessons.f1.complete,true);assert.throws(()=>validate({version:99},['f1']))});
test('malformed backups cannot pollute prototypes',()=>{const s=JSON.parse('{"app":"philosophy-scholar","version":1,"lessons":{"__proto__":{"bad":true},"f1":{"answers":{"__proto__":{"bad":true}}}},"notes":[],"daily":{"2026-09-07":{"words":3}}}');const r=validate(s,['f1']);assert.equal({}.bad,undefined);assert.equal(r.daily['2026-09-07'].seconds,0)});
test('storage failure is reported without losing in-memory progress',()=>{const store=createStore(['f1'],{getItem(){return null},setItem(){throw Error('quota')}});award(store.state,'q1',5);assert.equal(store.save(),false);assert.equal(store.state.xp,5);assert.match(store.error,/quota/)});

test('unfinished note survives validation and rejects malformed draft fields',()=>{const s=fresh();s.noteDraft={text:'A question',lesson:'f1',type:'question'};assert.deepEqual(validate(s,['f1']).noteDraft,s.noteDraft);s.noteDraft={text:42,lesson:'unknown',type:'invalid'};assert.deepEqual(validate(s,['f1']).noteDraft,{text:'',lesson:'f1',type:'note'});});
test('exemplar progress survives validation and rejects unsafe keys',()=>{const s=fresh();s.exemplars={'philosophy-reasons-exemplar':{responses:{'argument-parts':1,'reconstruct-reason':'A reason.'},attempts:{'argument-parts':2},passed:{'argument-parts':true},updatedAt:123}};const r=validate(s,['f1']);assert.equal(r.exemplars['philosophy-reasons-exemplar'].responses['reconstruct-reason'],'A reason.');assert.equal(r.exemplars['philosophy-reasons-exemplar'].passed['argument-parts'],true);const dirty=JSON.parse('{"exemplars":{"__proto__":{"bad":true},"lesson":{"responses":{"__proto__":"x"}}}}');const clean=validate({...fresh(),...dirty},['f1']);assert.equal(Object.hasOwn(clean.exemplars,'__proto__'),false);assert.equal({}.bad,undefined);});
